### ISSUE TITLE
Same-origin policy

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#7]
In Firefox (v42.0), the reason nothing is displayed seems to be that you break the same origin policy.

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

I found that out using developer tools of Firefox and saw this error:
`NS_ERROR_DOM_BAD_URI: Access to restricted URI denied`.

Might apply to Google Chrome as well.

A solution might follow that implemented here:

https://github.com/pierreganty/mist/tree/master/scripts

where no external data is fetched by instead a pre-processor `mustache` 
is run with the effect of filling the files with the data.

You should discuss with @pevalme about this.

**Comment by elenagutiv** [comment]
That's right!
I have just arrived to same conclusion now , when your html script
fetch data from local files, same origin policy says you are not
allowed to do that, and no data is shown. If I replace .css and .js
local file paths by urls (as you recommended in the email) this works
but when loading json data from my local file, the problem is still
there

Some solutions...:

Safari has a user option (enabling the developer menu, and selecting
"Disable local file restrictions" from the develop menu) that avoids
the issue.

Google Chrome can also be opened with the flag --disable-web-security
(in macOS you can run the following command in the terminal: open -a
"Google Chrome" --args --disable-web-security) and opening the html
script from the new window just launched will show everything
properly.

I suppose in Firefox you can do something similar, but it should be a
cleaner solution (in terms of security vulnerability)

I will ask Pedro about mustache.

Elena.

2015-11-16 11:32 GMT+01:00 pierreganty notifications@github.com:

**Comment by elenagutiv** [comment]
It seems there is no easy solution for Firefox (installing some stuff in the browser...), and these kinds of solutions dont seem trusty and simple. So, yes, definitely i will ask pedro about mustache.

**Comment by pierreganty** [comment]
What works is to copy `plot.json` in the `plot-scripts` directory and update the code accordingly.

**Comment by pierreganty** [comment]
What I suggest is to inline the data in json format in the JS code.
Look, they do right here: http://nvd3.org/examples/discreteBar.html.

To make it flexible, one solution (you might want to evaluate if there are better alternatives) is to
use a template language. @pevalme has experience using [mustache](https://mustache.github.io/) that would inline `plot.json` directly into the JS. Hence the `.html` file would be completely standalone.
Look at the scripts in the mist repository as indicated above.

**Comment by pierreganty** [comment]
Solved as of 6e341828e06f73099c3c0bb5ab0b96cd3465af38
